# Generated by Django 5.1.1 on 2024-09-21 22:44

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('hbl', models.TextField(blank=True, max_length=50)),
                ('merch_description', models.TextField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(blank=True, max_length=2)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('cbm', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('aduana_pay', models.IntegerField(blank=True, max_length=4)),
                ('category', models.TextField(blank=True, max_length=20)),
                ('pick_date', models.DateField()),
                ('name_last_name', models.TextField(blank=True, max_length=100)),
                ('ci', models.IntegerField(blank=True, max_length=11)),
                ('passaport', models.TextField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('municipy', models.TextField(blank=True, max_length=50)),
                ('province', models.TextField(blank=True, max_length=25)),
                ('postal_code', models.IntegerField(blank=True, max_length=10)),
                ('address2', models.TextField(blank=True, max_length=100)),
                ('municipy2', models.TextField(blank=True, max_length=50)),
                ('province2', models.TextField(blank=True, max_length=25)),
                ('postal_code2', models.IntegerField(blank=True, max_length=10)),
                ('latitud', models.FloatField(blank=True, max_length=30)),
                ('longitud', models.FloatField(blank=True, max_length=30)),
                ('phone', models.IntegerField(blank=True, max_length=15)),
                ('name_last_name2', models.TextField(blank=True, max_length=100)),
                ('mobile', models.IntegerField(blank=True, max_length=15)),
                ('email', models.TextField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
