# Generated by Django 5.1.1 on 2024-09-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='email2',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='mobile2',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='warehouse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
