# Generated by Django 5.1.1 on 2024-09-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transfer_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='warehouse',
            field=models.BooleanField(),
        ),
    ]
