# Generated by Django 5.1.1 on 2024-09-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transfer_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='warehouse',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
